### ISSUE TITLE
Unknown column 'flp_rules' in 'field list'

### ISSUE THREAD

**Issue by therampagerado** [fraudlabspro/thirtybees#1]
I get this error with v 1.0 for thirtybees.

I can get it working with an old version for PS 1.6.1 but I would like to also detect the device fingerprints. I also tried 1.1 (manual changes in the files) and it's not working also, I get an error on the last checkout step.

![image](https://github.com/fraudlabspro/thirtybees/assets/11251370/16141b89-629f-47b5-bc7a-0ed5b557cf6a)

**Comment by fraudlabspro-com** [comment]
Please update to version [1.1.0](https://github.com/fraudlabspro/thirtybees/releases/tag/1.1.0) for the fix.
