### ISSUE TITLE
version 1.1.0 error upon checkout

### ISSUE THREAD

**Issue by therampagerado** [fraudlabspro/thirtybees#2]
Hello there!

After an update to version 1.1.0 from github I get this error upon order completion:

![image](https://github.com/fraudlabspro/thirtybees/assets/11251370/94423807-78c3-4907-a03c-4b9a469d0b0d)

My module settings:

![image](https://github.com/fraudlabspro/thirtybees/assets/11251370/1fe9407a-2826-4dec-b855-6d779f02cf57)

My order is not completed and no data is recorded:

![image](https://github.com/fraudlabspro/thirtybees/assets/11251370/75e4e31c-49ba-4761-8b36-87e44534e5d3)

Also there are couple of warnings on php8 currently in my module settings page:

![image](https://github.com/fraudlabspro/thirtybees/assets/11251370/d27d49e1-0ad5-4a23-a708-7099ee2c84fd)

**Comment by fraudlabspro-com** [comment]
Can I know the version of ThirtyBees you have installed?

**Comment by therampagerado** [comment]
I'm running on edge channel.

Also on install the module complains that there is already module data installed with an exception but I did not shoot that. If you need it I'll reinstall and get a screen. After a refresh the module configuration is shown as per above.

**Comment by fraudlabspro-com** [comment]
Can you try to uninstall the module and install it back?
I cannot reproduce the errors under:
- ThirtyBees 1.5.1
- PHP 8.2.15

**Comment by fraudlabspro-com** [comment]
Please confirm you have removed the table "tb_orders_fraudlabspro" from MySQL as well, if it's not removed.

**Comment by therampagerado** [comment]
This is the error I get on reinstall and was talking about .

![image](https://github.com/fraudlabspro/thirtybees/assets/11251370/f043bc71-e954-49b6-beb0-4a569e732c93)

After I drop it and reinstall the module it installs correctly and I'm able to complete the order.

Then i get only 2 warnings in BO when opening an order with module 1.1.0 and edge thirtybees:


![image](https://github.com/fraudlabspro/thirtybees/assets/11251370/105f1341-81c8-4d6d-88f9-6e5504cb6dce)

EDIT:

And those warnings in module configuration page are still present:

![image](https://github.com/fraudlabspro/thirtybees/assets/11251370/30f8ef9a-34ee-4a36-82fd-ea40b3258a60)

**Comment by fraudlabspro-com** [comment]
Can I know what is the PHP version that running on your edge?

**Comment by therampagerado** [comment]
I'm on php8.0.xx Many of my other modules are having troubles on 8.1 and later.

**Comment by fraudlabspro-com** [comment]
It looks like your templates are cached.

Can you clear the system caches then try again?

**Comment by therampagerado** [comment]
Thank you. This helped for the order page but the ones in my module config page are still there:

![image](https://github.com/fraudlabspro/thirtybees/assets/11251370/f1443da0-baa4-4f19-90f5-f8c4a3da0784)


Collect logs modules says:

![image](https://github.com/fraudlabspro/thirtybees/assets/11251370/77476f5f-a48e-4bc3-a26b-6bbd14ac3bf9)


![image](https://github.com/fraudlabspro/thirtybees/assets/11251370/2b881ce3-8a1f-44a5-a29e-4472f293448e)

![image](https://github.com/fraudlabspro/thirtybees/assets/11251370/f89e8f83-a2b1-4294-9857-a9902926b698)


This is my test setup so I'm running debug mode on and I have Collect logs module installed where those get populated.

Thank you for your patience and for looking into it!

**Comment by fraudlabspro-com** [comment]
Can you please attach the cache file **xxxxx.file.form.tpl.php** so I can see the content?

**Comment by therampagerado** [comment]
Sorry for the delay

Here is the file.
[e06cfed517015cbd287048d5e753b34a359d8818_0.file.form.tpl.zip](https://github.com/fraudlabspro/thirtybees/files/14320029/e06cfed517015cbd287048d5e753b34a359d8818_0.file.form.tpl.zip)

**Comment by fraudlabspro-com** [comment]
Can you rename the follow file to **fraudlabspro.php** and replace your existing file in modules/fraudlabspro/ folder?

This should be fix the int warnings. Please make sure you clear your cache after you uploaded the file.

[fraudlabspro.php.txt](https://github.com/fraudlabspro/thirtybees/files/14324755/fraudlabspro.php.txt)

**Comment by therampagerado** [comment]
Thank you! This fixes those warnings!

One last question, I have not added manually the javascript for device detection but can see it's code in my source. Thus I'm not able to see this info in my dashboard. Is this feature only for paid plans?

**Comment by fraudlabspro-com** [comment]
All plans include device detection. It may take some time to collect the information.
