### ISSUE TITLE
Exception with high risk country.

### ISSUE THREAD

**Issue by therampagerado** [fraudlabspro/thirtybees#3]
![image](https://github.com/fraudlabspro/thirtybees/assets/11251370/93e3b37c-aadb-4ba6-940b-5e77854ac754)
INSERT INTO `ps_orders_fraudlabspro` (`id_order`, `is_country_match`, `is_high_risk_country`, `distance_in_km`, `distance_in_mile`, `ip_address`, `ip_country`, `ip_continent`, `ip_region`, `ip_city`, `ip_latitude`, `ip_longitude`, `ip_timezone`, `ip_elevation`, `ip_domain`, `ip_mobile_mnc`, `ip_mobile_mcc`, `ip_mobile_brand`, `ip_netspeed`, `ip_isp_name`, `ip_usage_type`, `is_free_email`, `is_new_domain_name`, `is_proxy_ip_address`, `is_bin_found`, `is_bin_country_match`, `is_bin_name_match`, `is_bin_phone_match`, `is_bin_prepaid`, `is_address_ship_forward`, `is_bill_ship_city_match`, `is_bill_ship_state_match`, `is_bill_ship_country_match`, `is_bill_ship_postal_match`, `is_ip_blacklist`, `is_email_blacklist`, `is_credit_card_blacklist`, `is_device_blacklist`, `is_user_blacklist`, `flp_score`, `flp_distribution`, `flp_status`, `flp_id`, `flp_error_code`, `flp_message`, `flp_credits`, `api_key`) VALUES ('1XXX', 'N', 'N', '2011.13', '1249.66', '217.66.158.40', 'RU', 'Asia', 'Leningradskaya oblast'', 'Volkhov', '59.9258', '32.3382', '+03:00', '32', 'mtsgsm.com', 'NA', 'NA', 'NA', 'DSL', 'MTS PJSC', 'Mobile ISP', 'Y', 'N', 'N', 'NA', 'NA', 'NA', 'NA', 'NA', 'N', 'Y', 'NA', 'Y', 'Y', '', 'N', 'NA', 'NA', 'NA', '60', '86', 'APPROVE', '20240218-XXXXX', '', '', '4XX', 'BXXXXXXXXXCK5GGLO3LAW2UYLVGFA0')

The order appears normal but it was not completed correctly for some reason, the status is not properly set in thirtybees and the fraudlabs module is not visible but the transaction is recorded in my dashboard (on your site).

![image](https://github.com/fraudlabspro/thirtybees/assets/11251370/0d71b7eb-b33f-4a76-9fcb-e0773189d57f)

**Comment by fraudlabspro-com** [comment]
Are you still not updated to version 1.1.0? This field is no longer available in the latest version.

**Comment by therampagerado** [comment]
Not on this site. Updated my test one. Will update this aswell.
