### ISSUE TITLE
POST https://api.fraudlabspro.com/v2/order/screen` resulted in a `504 Gateway Time-out` response:

### ISSUE THREAD

**Issue by therampagerado** [fraudlabspro/thirtybees#4]
![image](https://github.com/fraudlabspro/thirtybees/assets/11251370/f14e5e36-3079-47e0-a80e-586dad5487f4)

As of today our orders hang out with no order status because of this timeout. It would be nice if the orders complete normally if your server is not reachable because now the client sees error 500 at the last step.

**Comment by fraudlabspro-com** [comment]
It looks like one of the server was down. It's resolved now.

**Comment by therampagerado** [comment]
@fraudlabspro - today again we have one order that failed to complete properly and the customer saw errors at the last checkout step because the server was out.

Can you implement some fallback that checks and if the server is out simply record an order w/o Fraudlabs data in it?
